// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Models;

namespace server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210607072125_initrre")]
    partial class initrre
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("server.Models.BlogComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BlogPostId")
                        .HasColumnType("bigint");

                    b.Property<long>("BlogUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId");

                    b.HasIndex("BlogUserId");

                    b.ToTable("BlogComments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BlogPostId = 1L,
                            BlogUserId = 1L,
                            Comment = "Comment 1",
                            CommentDate = new DateTime(2021, 6, 6, 13, 21, 24, 434, DateTimeKind.Local).AddTicks(416)
                        },
                        new
                        {
                            Id = 2L,
                            BlogPostId = 1L,
                            BlogUserId = 2L,
                            Comment = "Comment 2",
                            CommentDate = new DateTime(2021, 6, 7, 13, 21, 24, 434, DateTimeKind.Local).AddTicks(1750)
                        },
                        new
                        {
                            Id = 3L,
                            BlogPostId = 1L,
                            BlogUserId = 1L,
                            Comment = "Comment 3",
                            CommentDate = new DateTime(2021, 6, 5, 13, 21, 24, 434, DateTimeKind.Local).AddTicks(1788)
                        },
                        new
                        {
                            Id = 4L,
                            BlogPostId = 2L,
                            BlogUserId = 3L,
                            Comment = "Comment 4",
                            CommentDate = new DateTime(2021, 6, 5, 13, 21, 24, 434, DateTimeKind.Local).AddTicks(1792)
                        },
                        new
                        {
                            Id = 5L,
                            BlogPostId = 2L,
                            BlogUserId = 4L,
                            Comment = "Comment 5",
                            CommentDate = new DateTime(2021, 6, 7, 13, 21, 24, 434, DateTimeKind.Local).AddTicks(1801)
                        },
                        new
                        {
                            Id = 6L,
                            BlogPostId = 3L,
                            BlogUserId = 5L,
                            Comment = "Comment 6",
                            CommentDate = new DateTime(2021, 6, 7, 13, 21, 24, 434, DateTimeKind.Local).AddTicks(1807)
                        },
                        new
                        {
                            Id = 7L,
                            BlogPostId = 3L,
                            BlogUserId = 6L,
                            Comment = "Comment 7",
                            CommentDate = new DateTime(2021, 6, 6, 13, 21, 24, 434, DateTimeKind.Local).AddTicks(1813)
                        },
                        new
                        {
                            Id = 8L,
                            BlogPostId = 3L,
                            BlogUserId = 4L,
                            Comment = "Comment 8",
                            CommentDate = new DateTime(2021, 6, 7, 13, 21, 24, 434, DateTimeKind.Local).AddTicks(1818)
                        },
                        new
                        {
                            Id = 9L,
                            BlogPostId = 4L,
                            BlogUserId = 6L,
                            Comment = "Comment 9",
                            CommentDate = new DateTime(2021, 6, 6, 13, 21, 24, 434, DateTimeKind.Local).AddTicks(1821)
                        });
                });

            modelBuilder.Entity("server.Models.BlogCommentLikeAndDislike", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BlogCommentId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BlogCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("BlogCommentLikeAndDislikes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BlogCommentId = 1L,
                            IsLike = true,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            BlogCommentId = 1L,
                            IsLike = true,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            BlogCommentId = 1L,
                            IsLike = false,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            BlogCommentId = 1L,
                            IsLike = false,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            BlogCommentId = 1L,
                            IsLike = false,
                            UserId = 5L
                        },
                        new
                        {
                            Id = 6L,
                            BlogCommentId = 1L,
                            IsLike = true,
                            UserId = 6L
                        },
                        new
                        {
                            Id = 7L,
                            BlogCommentId = 2L,
                            IsLike = true,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            BlogCommentId = 2L,
                            IsLike = true,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 9L,
                            BlogCommentId = 2L,
                            IsLike = false,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 10L,
                            BlogCommentId = 2L,
                            IsLike = true,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 11L,
                            BlogCommentId = 2L,
                            IsLike = false,
                            UserId = 5L
                        },
                        new
                        {
                            Id = 12L,
                            BlogCommentId = 2L,
                            IsLike = true,
                            UserId = 6L
                        },
                        new
                        {
                            Id = 13L,
                            BlogCommentId = 3L,
                            IsLike = true,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 14L,
                            BlogCommentId = 3L,
                            IsLike = true,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 16L,
                            BlogCommentId = 3L,
                            IsLike = false,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 17L,
                            BlogCommentId = 3L,
                            IsLike = true,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 18L,
                            BlogCommentId = 3L,
                            IsLike = false,
                            UserId = 5L
                        },
                        new
                        {
                            Id = 19L,
                            BlogCommentId = 3L,
                            IsLike = true,
                            UserId = 6L
                        },
                        new
                        {
                            Id = 20L,
                            BlogCommentId = 4L,
                            IsLike = true,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 21L,
                            BlogCommentId = 4L,
                            IsLike = true,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 22L,
                            BlogCommentId = 4L,
                            IsLike = false,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 23L,
                            BlogCommentId = 4L,
                            IsLike = true,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 24L,
                            BlogCommentId = 4L,
                            IsLike = false,
                            UserId = 5L
                        },
                        new
                        {
                            Id = 25L,
                            BlogCommentId = 4L,
                            IsLike = true,
                            UserId = 6L
                        },
                        new
                        {
                            Id = 26L,
                            BlogCommentId = 5L,
                            IsLike = true,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 27L,
                            BlogCommentId = 5L,
                            IsLike = true,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 28L,
                            BlogCommentId = 5L,
                            IsLike = false,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 29L,
                            BlogCommentId = 5L,
                            IsLike = true,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 30L,
                            BlogCommentId = 5L,
                            IsLike = false,
                            UserId = 5L
                        },
                        new
                        {
                            Id = 31L,
                            BlogCommentId = 5L,
                            IsLike = true,
                            UserId = 6L
                        },
                        new
                        {
                            Id = 32L,
                            BlogCommentId = 6L,
                            IsLike = true,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 33L,
                            BlogCommentId = 6L,
                            IsLike = true,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 34L,
                            BlogCommentId = 6L,
                            IsLike = false,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 35L,
                            BlogCommentId = 6L,
                            IsLike = true,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 36L,
                            BlogCommentId = 6L,
                            IsLike = false,
                            UserId = 5L
                        },
                        new
                        {
                            Id = 37L,
                            BlogCommentId = 6L,
                            IsLike = true,
                            UserId = 6L
                        },
                        new
                        {
                            Id = 38L,
                            BlogCommentId = 7L,
                            IsLike = true,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 39L,
                            BlogCommentId = 7L,
                            IsLike = true,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 40L,
                            BlogCommentId = 7L,
                            IsLike = false,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 41L,
                            BlogCommentId = 7L,
                            IsLike = false,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 42L,
                            BlogCommentId = 7L,
                            IsLike = false,
                            UserId = 5L
                        },
                        new
                        {
                            Id = 43L,
                            BlogCommentId = 7L,
                            IsLike = true,
                            UserId = 6L
                        },
                        new
                        {
                            Id = 44L,
                            BlogCommentId = 8L,
                            IsLike = false,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 45L,
                            BlogCommentId = 8L,
                            IsLike = false,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 46L,
                            BlogCommentId = 9L,
                            IsLike = false,
                            UserId = 5L
                        },
                        new
                        {
                            Id = 47L,
                            BlogCommentId = 9L,
                            IsLike = true,
                            UserId = 6L
                        });
                });

            modelBuilder.Entity("server.Models.BlogPost", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BlogUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlogUserId");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BlogUserId = 3L,
                            Post = "Blog 1",
                            PostDate = new DateTime(2021, 6, 7, 13, 21, 24, 431, DateTimeKind.Local).AddTicks(8867)
                        },
                        new
                        {
                            Id = 2L,
                            BlogUserId = 1L,
                            Post = "Blog 2",
                            PostDate = new DateTime(2021, 6, 5, 13, 21, 24, 433, DateTimeKind.Local).AddTicks(4909)
                        },
                        new
                        {
                            Id = 3L,
                            BlogUserId = 4L,
                            Post = "Blog 3",
                            PostDate = new DateTime(2021, 6, 6, 13, 21, 24, 433, DateTimeKind.Local).AddTicks(5093)
                        },
                        new
                        {
                            Id = 4L,
                            BlogUserId = 5L,
                            Post = "Blog 4",
                            PostDate = new DateTime(2021, 6, 6, 13, 21, 24, 433, DateTimeKind.Local).AddTicks(5103)
                        });
                });

            modelBuilder.Entity("server.Models.BlogUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("BlogUsers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            UserName = "User 1"
                        },
                        new
                        {
                            Id = 2L,
                            UserName = "User 2"
                        },
                        new
                        {
                            Id = 3L,
                            UserName = "User 3"
                        },
                        new
                        {
                            Id = 4L,
                            UserName = "User 4"
                        },
                        new
                        {
                            Id = 5L,
                            UserName = "User 5"
                        },
                        new
                        {
                            Id = 6L,
                            UserName = "User 6"
                        });
                });

            modelBuilder.Entity("server.Models.BlogComment", b =>
                {
                    b.HasOne("server.Models.BlogPost", "BlogPost")
                        .WithMany("BlogComments")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.BlogUser", "BlogUser")
                        .WithMany("BlogComments")
                        .HasForeignKey("BlogUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("server.Models.BlogCommentLikeAndDislike", b =>
                {
                    b.HasOne("server.Models.BlogComment", "BlogComment")
                        .WithMany("BlogCommentLikeAndDislikes")
                        .HasForeignKey("BlogCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.BlogUser", "BlogUser")
                        .WithMany("BlogCommentLikeAndDislikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("server.Models.BlogPost", b =>
                {
                    b.HasOne("server.Models.BlogUser", "BlogUser")
                        .WithMany()
                        .HasForeignKey("BlogUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
